#### [순환신경망 RNN] <hr>


In [1]:
import torch
import torch.nn as nn


In [2]:
### ------------------------------------------------------
### ===> 설계 : 다층 RNN, 층 2개
### ===> INPUT
### ------------------------------------------------------
### 입력 초기 텐서들
input = torch.randn(
    3, 50, 10
)  ## 배치사이즈, 시퀀스(1개 문장 구성 단어 수), 피쳐 수(1개 단어 표현하는 수)
h0 = torch.randn(2, 3, 5)  ## 히든 스테이트 초기화(양방향*층수, 배치사이즈, 히든 갯수)

### RNN 인스턴스
rnn = nn.RNN(10, 5, 2, batch_first=True)

### 출력 텐서들
output, hn = rnn(input, h0)


In [3]:
from torchinfo import summary

summary(rnn)


Layer (type:depth-idx)                   Param #
RNN                                      145
Total params: 145
Trainable params: 145
Non-trainable params: 0

In [4]:
## rnn 모델의 속성 출력
print(f"[all_weights] - {len(rnn.all_weights)}개")

for name, param in rnn.named_parameters():
    print(f"======> [{name}]\n{param.shape}\n")


[all_weights] - 2개
======> [weight_ih_l0]
torch.Size([5, 10])

======> [weight_hh_l0]
torch.Size([5, 5])

======> [bias_ih_l0]
torch.Size([5])

======> [bias_hh_l0]
torch.Size([5])

======> [weight_ih_l1]
torch.Size([5, 5])

======> [weight_hh_l1]
torch.Size([5, 5])

======> [bias_ih_l1]
torch.Size([5])

======> [bias_hh_l1]
torch.Size([5])



In [22]:
HIDDEN_SIZE = 3
NUM_LAYERS = 1
SEQ_LENGHT = 3
BATCH_SIZE = 1
BIDIRECTIONAL = True

### ===> 데이터 및 초기 Hidden state
input = torch.randn(
    BATCH_SIZE, SEQ_LENGHT, 10
)  # 입력 데이터 (배치 크기, 시퀀스 길이, 피쳐 길이)

### ===> 첫번째 Hidden state 초기값
h0 = torch.randn(
    NUM_LAYERS * (int(BIDIRECTIONAL) + 1), BATCH_SIZE, HIDDEN_SIZE
)  # 히든 초기값 (양방향*층수, 배치크기, 히든 개수)

### ===> RNN 인스턴스 생성
rnn = nn.RNN(10, HIDDEN_SIZE, NUM_LAYERS, batch_first=True, bidirectional=BIDIRECTIONAL)

### ===> RNN 출력
output, hn = rnn(input, h0)


In [23]:
print(f"[INPUT DATA]\n-SHAPE : {input.shape}   DIM : {input.ndim}D")


[INPUT DATA]
-SHAPE : torch.Size([1, 3, 10])   DIM : 3D


In [24]:
print(f"[RNN PARAMETERS]")
for name, param in rnn.named_parameters():
    print(f"----[{name}]\n{param}\n")


[RNN PARAMETERS]
----[weight_ih_l0]
Parameter containing:
tensor([[-0.1057, -0.2712, -0.1800, -0.4242, -0.2694,  0.2117, -0.0861,  0.3077,
         -0.2202,  0.3305],
        [ 0.2425,  0.4077,  0.2866,  0.2951,  0.0886, -0.1573,  0.4958, -0.0449,
          0.2740, -0.1110],
        [ 0.5045,  0.3408, -0.2811, -0.1442,  0.2346,  0.2547, -0.4024,  0.4469,
         -0.1057, -0.3720]], requires_grad=True)

----[weight_hh_l0]
Parameter containing:
tensor([[ 0.3550, -0.5027,  0.2564],
        [ 0.1375, -0.3519, -0.0140],
        [-0.4169,  0.1876,  0.2473]], requires_grad=True)

----[bias_ih_l0]
Parameter containing:
tensor([ 0.3946,  0.1945, -0.2364], requires_grad=True)

----[bias_hh_l0]
Parameter containing:
tensor([-0.0918, -0.0548, -0.1488], requires_grad=True)

----[weight_ih_l0_reverse]
Parameter containing:
tensor([[-0.1206, -0.1830,  0.1229,  0.2046, -0.5525,  0.0225,  0.3197, -0.1280,
          0.4794,  0.0610],
        [ 0.5122,  0.4880, -0.1163,  0.2474, -0.5221, -0.1936,  0.366

In [25]:
print(f"[RNN 출력 - output]\n-SHAPE : {output.shape}   DIM : {output.ndim}D")
print(output)


[RNN 출력 - output]
-SHAPE : torch.Size([1, 3, 6])   DIM : 3D
tensor([[[-0.4828,  0.2618,  0.7598, -0.3546,  0.8051, -0.5287],
         [ 0.5410, -0.6237, -0.3441, -0.7498,  0.2674, -0.9503],
         [-0.3065,  0.9644,  0.4899, -0.5384,  0.9878, -0.3322]]],
       grad_fn=<TransposeBackward1>)


In [26]:
print(f"[RNN 출력 - hn]\n-SHAPE : {hn.shape}   DIM : {hn.ndim}D")
print(hn)


[RNN 출력 - hn]
-SHAPE : torch.Size([2, 1, 3])   DIM : 3D
tensor([[[-0.3065,  0.9644,  0.4899]],

        [[-0.3546,  0.8051, -0.5287]]], grad_fn=<StackBackward0>)
