#### [순환신경망 RNN] <hr>


In [1]:
import torch
import torch.nn as nn


In [2]:
### ------------------------------------------------------
### ===> 설계 : 다층 RNN, 층 2개
### ===> INPUT
### ------------------------------------------------------
### 입력 초기 텐서들
input = torch.randn(
    3, 50, 10
)  ## 배치사이즈, 시퀀스(1개 문장 구성 단어 수), 피쳐 수(1개 단어 표현하는 수)
h0 = torch.randn(2, 3, 5)  ## 히든 스테이트 초기화(양방향*층수, 배치사이즈, 히든 갯수)

### RNN 인스턴스
rnn = nn.RNN(10, 5, 2, batch_first=True)

### 출력 텐서들
output, hn = rnn(input, h0)


In [3]:
from torchinfo import summary

summary(rnn)


Layer (type:depth-idx)                   Param #
RNN                                      145
Total params: 145
Trainable params: 145
Non-trainable params: 0

In [4]:
## rnn 모델의 속성 출력
print(f"[all_weights] - {len(rnn.all_weights)}개")

for name, param in rnn.named_parameters():
    print(f"======> [{name}]\n{param.shape}\n")


[all_weights] - 2개
======> [weight_ih_l0]
torch.Size([5, 10])

======> [weight_hh_l0]
torch.Size([5, 5])

======> [bias_ih_l0]
torch.Size([5])

======> [bias_hh_l0]
torch.Size([5])

======> [weight_ih_l1]
torch.Size([5, 5])

======> [weight_hh_l1]
torch.Size([5, 5])

======> [bias_ih_l1]
torch.Size([5])

======> [bias_hh_l1]
torch.Size([5])



In [16]:
HIDDEN_SIZE = 3
NUM_LAYERS = 1
SEQ_LENGHT = 3
BATCH_SIZE = 1

### ===> 데이터 및 초기 Hidden state
input = torch.randn(
    BATCH_SIZE, SEQ_LENGHT, 10
)  # 입력 데이터 (배치 크기, 시퀀스 길이, 피쳐 길이)

### ===> 첫번째 Hidden state 초기값
h0 = torch.randn(
    NUM_LAYERS, BATCH_SIZE, HIDDEN_SIZE
)  # 히든 초기값 (양방향*층수, 배치크기, 히든 개수)

### ===> RNN 인스턴스 생성
rnn = nn.RNN(10, HIDDEN_SIZE, NUM_LAYERS, batch_first=True)

### ===> RNN 출력
output, hn = rnn(input, h0)


In [17]:
print(f"[INPUT DATA]\n-SHAPE : {input.shape}   DIM : {input.ndim}D")


[INPUT DATA]
-SHAPE : torch.Size([1, 3, 10])   DIM : 3D


In [18]:
print(f"[RNN PARAMETERS]")
for name, param in rnn.named_parameters():
    print(f"----[{name}]\n{param}\n")


[RNN PARAMETERS]
----[weight_ih_l0]
Parameter containing:
tensor([[-0.0674, -0.4093,  0.2795,  0.0502,  0.1387,  0.0729,  0.2753, -0.5149,
         -0.4810, -0.2664],
        [ 0.3119, -0.2432,  0.1149,  0.4762,  0.5684, -0.1952,  0.0202, -0.3933,
          0.0554,  0.1394],
        [-0.0757,  0.0732, -0.3184, -0.2470, -0.1021, -0.3239,  0.5116, -0.2408,
         -0.2251,  0.1089]], requires_grad=True)

----[weight_hh_l0]
Parameter containing:
tensor([[-0.3910,  0.4964, -0.4348],
        [-0.1372, -0.0386, -0.1769],
        [-0.4546,  0.1569,  0.1598]], requires_grad=True)

----[bias_ih_l0]
Parameter containing:
tensor([-0.2784,  0.2083,  0.0956], requires_grad=True)

----[bias_hh_l0]
Parameter containing:
tensor([0.4557, 0.2951, 0.3641], requires_grad=True)



In [19]:
print(f"[RNN 출력 - output]\n-SHAPE : {output.shape}   DIM : {output.ndim}D")
print(output)


[RNN 출력 - output]
-SHAPE : torch.Size([1, 3, 3])   DIM : 3D
tensor([[[ 0.8427,  0.4013,  0.7881],
         [-0.7584, -0.6894,  0.6568],
         [-0.6575, -0.4768,  0.1764]]], grad_fn=<TransposeBackward1>)


In [20]:
print(f"[RNN 출력 - hn]\n-SHAPE : {hn.shape}   DIM : {hn.ndim}D")
print(hn)


[RNN 출력 - hn]
-SHAPE : torch.Size([1, 1, 3])   DIM : 3D
tensor([[[-0.6575, -0.4768,  0.1764]]], grad_fn=<StackBackward0>)
